name: 'food_recall'
version: '1.0.0'

profile: 'food_recall'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  food_recall:
    staging:
      +materialized: view
    marts:
      +materialized: table
